### ISSUE TITLE
Google Daylight Calendar

### ISSUE THREAD

**Issue by justleifrn** [chrisblakley/Daylight-Calendar-ICS#19]
"[Find your geo coordinates](http://mygeoposition.com/)"
I am unable to figure out how to make Chrome allow me to access this site: "insecure" won't give out my location
so why not use/suggest https://www.latlong.net/
instead.

**Comment by chrisblakley** [comment]
Good catch– I didn't realize that site no longer worked. I'll update it to the one you shared. Thanks!
