### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by bholtdwyer** [chrisblakley/Daylight-Calendar-ICS#5]
This is not really an "issue", but I was wondering if it would be possible for you to make a minor modification so that instead of showing one single event all day, the url pointed to a calendar with two separate short "events", one for sunrise (or the start of civil daylight, or nautical daylight, etc.) and one for sunset (civil sunset, nautical sunset...). Currently the calendar produces one long event which "squishes" all other events on the calendar; it would be nice to just see sunrise and sunset as distinct events during the day. Thanks so much for making this calendar available!

**Comment by chrisblakley** [comment]
That's a really great idea– and yeah I wish there was a way for it to be in the background without affecting the size of actual calendar events.

If/when I do this, it'll probably be a separate endpoint, but could be a fun weekend project.

Thanks!

**Comment by megamorphg** [comment]
Another useful way is to have it as an "all-day" event and the Sunrise, Sunset information within the title of the event. Then it is easily visible on calendars without interfering with any events. However, this means timely notifications for a morning sunbath won't be able to be setup.

Anyway, it is probably possible to do this with some regex replaces on the current ICS but my regex is not that great.

**Comment by luxcalor** [comment]
Separate events with identical start and end times would be great. This way it would look nice in variety of calendars and allow for notifications etc without overwhelming the event list. Hope you can imlement this. Thanks for the effort!

**Comment by luxcalor** [comment]
I am glad to test it, how should I add the links you provided to Google calendar with my geo coordinates?

**Comment by megamorphg** [comment]
This works awesome! For reference this is what I used:
https://gearside.com/calendars/sun.ics?actual&lat=LATITUDE&lng=LONGITUDE&gmt=-7

**Comment by luxcalor** [comment]
Nice! It works great. One thing I would really prefer is an option for the start and end time for the events to be identical, so the duration would be 0. This way it doesn't clutter the calender and shows exact times between sunset, sunrise and other events. 
![S11130-23435788](https://user-images.githubusercontent.com/76074147/144133051-1316f298-c973-4ed4-87c9-658a941765b2.jpg)

**Comment by chrisblakley** [comment]
Easy enough– I added a `&length=15` parameter that controls the length of the actual sunrise/sunset event. Use minutes in this parameter. Default is 15 (if it is not present).

I actually have no idea how this will work if set to 0, but give it a try and see if it does what you're hoping.

https://gearside.com/calendars/sun.ics?actual &length=0

**Comment by luxcalor** [comment]
It worked perfectly fine set to 0! I did test 5 and 30 minutes and those settings worked great too. Thank you very much!

**Comment by dstorozhuk** [comment]
@chrisblakley can you share the new code? I want to modify to get the all-day event like this 
<img width="1306" alt="Google Calendar - Week of November 29, 2021 2021-12-05 14-26-09" src="https://user-images.githubusercontent.com/2509744/144746487-fe1c4062-eb1f-43d6-8627-2e1ce72c70f7.png">

**Comment by chrisblakley** [comment]
Yep– I'll get this pushed to this repo probably later today.

If you make the all-day event an option in the same file or if you make it as a completely separate file, feel free to make a PR and I'll include it in the repo as well!

**Comment by chrisblakley** [comment]
Commit is pushed to the repo as `sun.php`. I'm going to close this issue as the commit resolves this for now. Any additional feature requests can go in new issues, or feel free to re-open this if it is specific enough.
