### ISSUE TITLE
Something's jacked up

### ISSUE THREAD

**Issue by gitanO0** [chrisblakley/Daylight-Calendar-ICS#8]
This calendar was working great until about 2/10/23.  Now, it doesn't show any "events" and when I look at the URL in debug mode, the dates are pretty messed up.  What's going on?

**Comment by chrisblakley** [comment]
Thanks for the heads up- I did push an update a few days ago right before going out of town, heh what a smart idea.

I'll get this working again at some point today.

**Comment by chrisblakley** [comment]
I got it going again now. It'll prob take up to 12 hours for Google Calendar to re-fetch it.

**Comment by gitanO0** [comment]
Indeed.  Looks good now.  Thank you !
